#
# Module manifest for module 'Hyper-V'
#
# Generated by: Microsoft Corporation
#

@{

# Script module or binary module file associated with this manifest
RootModule = 'Microsoft.HyperV.PowerShell.dll'

# Version number of this module.
ModuleVersion = '1.1'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'af4bddd0-8583-4ff2-84b2-a33f5c8de8a7'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'Hyper-V.Types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Hyper-V.Format.ps1xml'

# Cmdlets to export from this module
CmdletsToExport = @(
    'Add-VMDvdDrive',
    'Add-VMFibreChannelHba',
    'Add-VMHardDiskDrive',
    'Add-VMMigrationNetwork',
    'Add-VMNetworkAdapter',
    'Add-VMNetworkAdapterAcl',
    'Add-VMNetworkAdapterExtendedAcl',
    'Add-VmNetworkAdapterRoutingDomainMapping',
    'Add-VMRemoteFx3dVideoAdapter',
    'Add-VMScsiController',
    'Add-VMStoragePath',
    'Add-VMSwitch',
    'Add-VMSwitchExtensionPortFeature',
    'Add-VMSwitchExtensionSwitchFeature',
    'Checkpoint-VM',
    'Compare-VM',
    'Complete-VMFailover',
    'Connect-VMNetworkAdapter',
    'Connect-VMSan',
    'Convert-VHD',
    'Copy-VMFile',
    'Debug-VM',
    'Disable-VMEventing',
    'Disable-VMIntegrationService',
    'Disable-VMMigration',
    'Disable-VMRemoteFXPhysicalVideoAdapter',
    'Disable-VMResourceMetering',
    'Disable-VMSwitchExtension',
    'Disconnect-VMNetworkAdapter',
    'Disconnect-VMSan',
    'Dismount-VHD',
    'Enable-VMEventing',
    'Enable-VMIntegrationService',
    'Enable-VMMigration',
    'Enable-VMRemoteFXPhysicalVideoAdapter',
    'Enable-VMReplication',
    'Enable-VMResourceMetering',
    'Enable-VMSwitchExtension',
    'Export-VM',
    'Export-VMSnapshot',
    'Get-VHD',
    'Get-VM',
    'Get-VMBios',
    'Get-VMComPort',
    'Get-VMConnectAccess',
    'Get-VMDvdDrive',
    'Get-VMFibreChannelHba',
    'Get-VMFirmware',
    'Get-VMFloppyDiskDrive',
    'Get-VMHardDiskDrive',
    'Get-VMHost',
    'Get-VMHostNumaNode',
    'Get-VMHostNumaNodeStatus',
    'Get-VMIdeController',
    'Get-VMIntegrationService',
    'Get-VMMemory',
    'Get-VMMigrationNetwork',
    'Get-VMNetworkAdapter',
    'Get-VMNetworkAdapterAcl',
    'Get-VMNetworkAdapterExtendedAcl',
    'Get-VMNetworkAdapterFailoverConfiguration',
    'Get-VmNetworkAdapterIsolation',
    'Get-VMNetworkAdapterRoutingDomainMapping',
    'Get-VMNetworkAdapterVlan',
    'Get-VMProcessor',
    'Get-VMRemoteFx3dVideoAdapter',
    'Get-VMRemoteFXPhysicalVideoAdapter',
    'Get-VMReplication',
    'Get-VMReplicationAuthorizationEntry',
    'Get-VMReplicationServer',
    'Get-VMResourcePool',
    'Get-VMSan',
    'Get-VMScsiController',
    'Get-VMSnapshot',
    'Get-VMStoragePath',
    'Get-VMSwitch',
    'Get-VMSwitchExtension',
    'Get-VMSwitchExtensionPortData',
    'Get-VMSwitchExtensionPortFeature',
    'Get-VMSwitchExtensionSwitchData',
    'Get-VMSwitchExtensionSwitchFeature',
    'Get-VMSystemSwitchExtension',
    'Get-VMSystemSwitchExtensionPortFeature',
    'Get-VMSystemSwitchExtensionSwitchFeature',
    'Grant-VMConnectAccess',
    'Import-VM',
    'Import-VMInitialReplication',
    'Measure-VM',
    'Measure-VMReplication',
    'Measure-VMResourcePool',
    'Merge-VHD',
    'Mount-VHD',
    'Move-VM',
    'Move-VMStorage',
    'New-VFD',
    'New-VHD',
    'New-VM',
    'New-VMReplicationAuthorizationEntry',
    'New-VMResourcePool',
    'New-VMSan',
    'New-VMSwitch',
    'Optimize-VHD',
    'Remove-VM',
    'Remove-VMDvdDrive',
    'Remove-VMFibreChannelHba',
    'Remove-VMHardDiskDrive',
    'Remove-VMMigrationNetwork',
    'Remove-VMNetworkAdapter',
    'Remove-VMNetworkAdapterAcl',
    'Remove-VMNetworkAdapterExtendedAcl',
    'Remove-VMNetworkAdapterRoutingDomainMapping',
    'Remove-VMRemoteFx3dVideoAdapter',
    'Remove-VMReplication',
    'Remove-VMReplicationAuthorizationEntry',
    'Remove-VMResourcePool',
    'Remove-VMSan',
    'Remove-VMSavedState',
    'Remove-VMScsiController',
    'Remove-VMSnapshot',
    'Remove-VMStoragePath',
    'Remove-VMSwitch',
    'Remove-VMSwitchExtensionPortFeature',
    'Remove-VMSwitchExtensionSwitchFeature',
    'Rename-VM',
    'Rename-VMNetworkAdapter',
    'Rename-VMResourcePool',
    'Rename-VMSan',
    'Rename-VMSnapshot',
    'Rename-VMSwitch',
    'Repair-VM',
    'Reset-VMReplicationStatistics',
    'Reset-VMResourceMetering',
    'Resize-VHD',
    'Restart-VM',
    'Restore-VMSnapshot',
    'Resume-VM',
    'Resume-VMReplication',
    'Revoke-VMConnectAccess',
    'Save-VM',
    'Set-VHD',
    'Set-VM',
    'Set-VMBios',
    'Set-VMComPort',
    'Set-VMDvdDrive',
    'Set-VMFibreChannelHba',
    'Set-VMFirmware',
    'Set-VMFloppyDiskDrive',
    'Set-VMHardDiskDrive',
    'Set-VMHost',
    'Set-VMMemory',
    'Set-VMMigrationNetwork',
    'Set-VMNetworkAdapter',
    'Set-VMNetworkAdapterFailoverConfiguration',
    'Set-VmNetworkAdapterIsolation',
    'Set-VmNetworkAdapterRoutingDomainMapping',
    'Set-VMNetworkAdapterVlan',
    'Set-VMProcessor',
    'Set-VMRemoteFx3dVideoAdapter',
    'Set-VMReplication',
    'Set-VMReplicationAuthorizationEntry',
    'Set-VMReplicationServer',
    'Set-VMResourcePool',
    'Set-VMSan',
    'Set-VMSwitch',
    'Set-VMSwitchExtensionPortFeature',
    'Set-VMSwitchExtensionSwitchFeature',
    'Start-VM',
    'Start-VMFailover',
    'Start-VMInitialReplication',
    'Stop-VM',
    'Stop-VMFailover',
    'Stop-VMInitialReplication',
    'Stop-VMReplication',
    'Suspend-VM',
    'Suspend-VMReplication',
    'Test-VHD',
    'Test-VMNetworkAdapter',
    'Test-VMReplicationConnection')
    
# Aliases to export from this module
AliasesToExport = @(
    'gvm',
    'savm',
    'spvm',
    'gvmr',
    'mvmr',
    'gvmrs')

# HelpInfo
HelpInfoUri="https://go.microsoft.com/fwlink/?linkid=285748"

}
