version: '3'
services: 
  jellyfin: 
    container_name: jellyfin
    depends_on: 
      - nginx_proxy
    devices: 
      - "/dev/dri:/dev/dri"
    environment: 
      - JELLYFIN_PublishedServerUrl="https://travisflix.com"
      - JELLYFIN_MEDIA_DIR=/media
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_CONFIG_DIR=/config/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_WEB_DIR=/jellyfin/jellyfin-web
      - JELLYFIN_FFMPEG=/usr/lib/jellyfin-ffmpeg/ffmpeg
    image: jellyfin/jellyfin:10.7.6
#deploy:
#resources:
#limits:
#memory: 3072m
    network_mode: host
    restart: unless-stopped
    volumes: 
      - "/usr/local/jellyfin/config:/config"
      - "/usr/local/jellyfin/media:/media:ro"
      - "/usr/local/jellyfin/cache:/cache"
      - "/usr/local/jellyfin/jellyfin-web:/jellyfin/jellyfin-web/src"

  nginx_proxy: 
    container_name: nginx
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    image: ghcr.io/linuxserver/nginx:latest
    networks: 
      - linuxserver-nginx_default
    ports: 
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes: 
      - "/usr/local/linuxserver-nginx/config:/config"
      - "/run/nginx-cache:/config/nginx-cache"

  pwndrop:
    depends_on:
      - nginx_proxy
    container_name: pwndrop
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - SECRET_PATH=/pwndrop
    image: ghcr.io/linuxserver/pwndrop:latest
    volumes:
      - /usr/local/pwndrop/config:/config
    ports:
      - "8080:8080"
    networks:
      - linuxserver-nginx_default
    restart: unless-stopped

  openspeedtest:
    depends_on:
      - nginx_proxy
    container_name: openspeedtest
    image: openspeedtest/latest:latest
    networks:
      - linuxserver-nginx_default
    ports:
      - "3000:3000"
    restart: unless-stopped

  letsencrypt:
    depends_on:
      - nginx_proxy
    image: ghcr.io/linuxserver/letsencrypt:latest
    networks:
      - linuxserver-nginx_default
    container_name: letsencryptpnw
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
      - URL=pnwpanorama.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /docker_data/nginx/config:/config
    ports:
      - "4433:443"
      - "8082:80"
    restart: unless-stopped

networks: 
  linuxserver-nginx_default:
    external: true
    name: linuxserver-nginx_default
