version: '3'
services:
  transmission-vpn:
    image: haugene/transmission-openvpn
    container_name: transmission-vpn
    restart: unless-stopped
    ports:
      - '9091:9091'
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=1" # ipv6 must be enabled for Mullvad to work
    volumes:
      - /docker/transmission-vpn/config:/config
      - /docker/transmission-vpn/data:/data
    environment:
      - TZ=America/Los_Angeles
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_USERNAME=user
      - PENVPN_PASSWORD=password
      - OPENVPN_CONFIG=au_all
       # - LOCAL_NETWORK=$LAN
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_USERNAME=visualblind
      - TRANSMISSION_RPC_PASSWORD=1cecream
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=1
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/data
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
      - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
      - TRANSMISSION_WATCH_DIR_ENABLED=false
      - TRANSMISSION_WATCH_DIR=$WATCHDIR
      - LOG_TO_STDOUT=true
