#!/bin/bash

# require library functions
SCRIPTPATH="$(readlink -f 2>/dev/null || perl -MCwd -e 'print Cwd::abs_path shift' $0)"
source "$(dirname "${SCRIPTPATH}")/lib.sh"

git2_search_base_dir


append=`echo "${GITTWO_DIRNAME}" | sed -e 's/\.//g'`

create_exclude git2 "${GITTWO_BASE}.git" "${append}"

