apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee 
  namespace: special
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee-special 
    service: coffee-special-svc
    port: 80
  subroutes:
  - path: /special 
    action:
      pass: coffee-special