apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      containers:
      - command: ["/run.sh", "http://nginxplus:8080"]
        name: autoscaler
        image: gcr.io/<project-id>/autoscaler
        imagePullPolicy: Always
