version: '3.3'
services: 
  jellyfin: 
    container_name: jellyfin
    devices: 
      - "/dev/dri:/dev/dri"
    environment: 
      - JELLYFIN_PublishedServerUrl=travisflix.com
      - JELLYFIN_MEDIA_DIR=/media
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_CONFIG_DIR=/config/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_WEB_DIR=/jellyfin/jellyfin-web
      - JELLYFIN_FFMPEG=/usr/lib/jellyfin-ffmpeg/ffmpeg
      - PUID=0
      - PGID=0
    image: jellyfin/jellyfin:latest
    network_mode: host
    restart: unless-stopped
    volumes: 
      - "/usr/local/jellyfin/config:/config"
      - "/mnt/mergerfs/media:/media:ro"
      - "/usr/local/jellyfin/cache:/cache"
      - "/usr/local/jellyfin/jellyfin-web:/jellyfin/jellyfin-web/src"
      - "/usr/local/jellyfin/jellyfin-web/config.json:/jellyfin/jellyfin-web/config.json"
      - "/usr/local/jellyfin/jellyfin-web/session-login-index-html.384c1886b01202a35d87.chunk.js:/jellyfin/jellyfin-web/session-login-index-html.384c1886b01202a35d87.chunk.js"

  filebrowser:
    container_name: filebrowser
    environment:
      - TZ=America/Los_Angeles
      - FB_BASEURL=/
      - FB_USERNAME=visualblind
    image: hurlenko/filebrowser
#user: "${UID}:${GID}"
    volumes:
      - /usr/local/filebrowser/config:/config
      - /usr/local/filebrowser/data:/data
      - /usr/local/filebrowser/branding:/branding
      - /mnt/mergerfs/media:/data/media:ro
      - /mnt/mergerfs/media/video-movies:/data/video-movies:ro
      - /mnt/mergerfs/media/video-movies:/data/users/upload/video-movies:ro
      - /mnt/p0ds0smb/media/video-tech:/data/users/upload/video-tech:ro
      - /mnt/p1ds0smb/software_wintel:/data/users/upload/software_wintel:ro
      - /mnt/mergerfs/backup:/data/backup:ro
    ports:
      - 8080:8080
    networks:
      - linuxserver-nginx_default
    restart: unless-stopped

  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest:latest
    networks:
      - linuxserver-nginx_default
    ports:
      - "3000:3000"
    restart: unless-stopped

  portainer:
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "/usr/local/portainer/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    image: portainer/portainer
    networks:
      - linuxserver-nginx_default

  webgrabplus:
    image: lscr.io/linuxserver/webgrabplus:latest
    container_name: webgrabplus
    hostname: webgrabplus
#   mac_address: 00:00:00:00:00:00
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /usr/local/webgrabplus/config:/config
      - /usr/local/webgrabplus/data:/data
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /usr/local/jellyseer/appdata/config:/app/config
    networks:
      - linuxserver-nginx_default
    restart: unless-stopped

  droppy:
    container_name: droppy
    image: silverwind/droppy
    ports:
      - '8083:8989'
    volumes:
      - /docker/droppy/config:/config
      - /docker/droppy/files:/files
    networks:
      - linuxserver-nginx_default
    restart: unless-stopped

networks: 
  linuxserver-nginx_default:
    external: true
    name: linuxserver-nginx_default
