
@{
    GUID = 'FAA199B6-C378-4AAD-9D4D-F0E99F3F4845'
    Author="Microsoft Corporation"
    CompanyName="Microsoft Corporation"
    Copyright="© Microsoft Corporation. All rights reserved."
    HelpInfoUri="http://go.microsoft.com/fwlink/?linkid=390771"
    NestedModules = @('FsrmAction.cdxml', 'FsrmAdrSetting.cdxml', 'FSRMAutoQuota.cdxml', 'FSRMClassification.cdxml', 'FSRMClassificationPropertyDefinition.cdxml', 'FSRMClassificationRule.cdxml', 'FSRMEffectiveNamespace.cdxml', 'FSRMFileManagementJob.cdxml', 'FsrmFmjAction.cdxml', 'FSRMFmjCondition.cdxml', 'FSRMFmjNotification.cdxml', 'FsrmFmjNotificationAction.cdxml', 'FsrmMacro.cdxml', 'FsrmMgmtProperty.cdxml', 'FsrmQuota.cdxml', 'FsrmQuotaTemplate.cdxml', 'FSRMQuotaThreshold.cdxml', 'FsrmSetting.cdxml', 'FsrmTestEmail.cdxml', 'FsrmFileGroup.cdxml', 'FsrmFileScreen.cdxml', 'FsrmFileScreenException.cdxml', 'FsrmFileScreenTemplate.cdxml', 'FsrmScheduledTask.cdxml', 'FsrmStorageReport.cdxml', 'FsrmMgmtProperty.cdxml', 'FsrmRmsTemplate.cdxml', 'FsrmClassificationPropertyValue.cdxml')
    FormatsToProcess = @('FsrmMgmtProperty.format.ps1xml')
    TypesToProcess = @('FsrmAction.types.ps1xml', 'FsrmAdrSetting.types.ps1xml', 'FsrmClassification.types.ps1xml', 'FSRMClassificationPropertyDefinition.types.ps1xml', 'FsrmClassificationRule.types.ps1xml', 'FsrmFileManagementJob.types.ps1xml', 'FsrmFmjAction.types.ps1xml', 'FsrmFmjCondition.types.ps1xml', 'FsrmFmjNotificationAction.types.ps1xml', 'FsrmMacro.types.ps1xml', 'FsrmScheduledTask.types.ps1xml', 'FsrmSetting.types.ps1xml', 'FsrmStorageReport.types.ps1xml')
    ModuleVersion = '2.0.0.0'
    AliasesToExport = @()
    PowerShellVersion = '5.1'
    FunctionsToExport = @('New-FSRMAction', 'Get-FsrmAdrSetting', 'Set-FsrmAdrSetting', 'New-FSRMAutoQuota', 'Get-FSRMAutoQuota', 'Remove-FSRMAutoQuota', 'Set-FSRMAutoQuota', 'Update-FSRMAutoQuota', 'Start-FSRMClassification', 'Wait-FSRMClassification', 'Stop-FSRMClassification', 'Get-FSRMClassification', 'Set-FSRMClassification', 'New-FSRMClassificationpropertyDefinition', 'Update-FSRMClassificationpropertyDefinition', 'Get-FSRMClassificationpropertyDefinition', 'Remove-FSRMClassificationpropertyDefinition', 'Set-FSRMClassificationpropertyDefinition', 'New-FSRMClassificationRule', 'Get-FSRMClassificationRule', 'Remove-FSRMClassificationRule', 'Set-FSRMClassificationRule', 'Get-FsrmEffectiveNamespace', 'New-FsrmFileGroup', 'Get-FsrmFileGroup', 'Remove-FsrmFileGroup', 'Set-FsrmFileGroup', 'New-FSRMFileManagementJob', 'Get-FSRMFileManagementJob', 'Remove-FSRMFileManagementJob', 'Set-FSRMFileManagementJob', 'Start-FSRMFileManagementJob', 'Wait-FSRMFileManagementJob', 'Stop-FSRMFileManagementJob', 'New-FsrmFileScreen', 'Get-FsrmFileScreen', 'Remove-FsrmFileScreen', 'Set-FsrmFileScreen', 'Reset-FsrmFileScreen', 'New-FsrmFileScreenException', 'Get-FsrmFileScreenException', 'Remove-FsrmFileScreenException', 'Set-FsrmFileScreenException', 'New-FsrmFileScreenTemplate', 'Get-FsrmFileScreenTemplate', 'Remove-FsrmFileScreenTemplate', 'Set-FsrmFileScreenTemplate', 'New-FSRMFmjAction', 'New-FSRMFmjCondition', 'New-FSRMFMJNotification', 'New-FsrmFmjNotificationAction', 'Get-FsrmMacro', 'Get-FSRMMgmtProperty', 'Set-FSRMMgmtProperty', 'Remove-FSRMMgmtProperty', 'New-FSRMQuota', 'Get-FSRMQuota', 'Remove-FSRMQuota', 'Set-FSRMQuota', 'Reset-FSRMQuota', 'Update-FSRMQuota', 'New-FSRMQuotaTemplate', 'Get-FSRMQuotaTemplate', 'Remove-FSRMQuotaTemplate', 'Set-FSRMQuotaTemplate', 'New-FSRMQuotaThreshold', 'Get-FsrmRmsTemplate', 'New-FsrmScheduledTask', 'Get-FsrmSetting', 'Set-FsrmSetting', 'New-FsrmStorageReport', 'Get-FsrmStorageReport', 'Remove-FsrmStorageReport', 'Set-FsrmStorageReport', 'Start-FsrmStorageReport', 'Wait-FsrmStorageReport', 'Stop-FsrmStorageReport', 'Send-FsrmTestEmail', 'New-FsrmClassificationPropertyValue')
    CompatiblePSEditions = @('Desktop', 'Core')
}
