version: '3.7'

networks:
  # communication to web and clients
  torrentsexternalproxy:
  # communication between lemmy services
  torrentsinternal:
    driver: bridge
    internal: true

services:
  proxy:
    image: nginx:1-alpine
    networks:
      - torrentsinternal
      - torrentsexternalproxy
    ports:
    # actual and only port facing any connection from outside 
      - "8904:8904"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - torrents-csv
      - torrents-csv-ui-perseus

  torrents-csv:
    image: dessalines/torrents-csv-server:latest
    restart: always
    hostname: torrents-csv
    networks:
      - torrentsinternal
    environment:
      TORRENTS_CSV_DB_FILE: /app/torrents.db 
      TORRENTS_CSV_FRONT_END_DIR: /app/dist

  torrents-csv-ui-perseus:
    image: dessalines/torrents-csv-ui-perseus:latest
    restart: always
    networks:
      - torrentsinternal
    environment:
      PERSEUS_HOST: "0.0.0.0"
      TORRENTS_CSV_ENDPOINT: "http://torrents-csv:8902"
    

