apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/<project-id>/backend
        ports:
        - containerPort: 5683
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  clusterIP: None
  ports:
  - port: 5683
    targetPort: 5683
    protocol: TCP
  selector:
    app: backend
