/*ALTER DATABASE HCM_CHCC SET OFFLINE
GO
ALTER DATABASE HCM_CHCC SET ONLINE
GO
*/
ALTER
DATABASE HCM_CHUC
SET
SINGLE_USER With
ROLLBACK IMMEDIATE

ALTER DATABASE HCM_CHUC MODIFY NAME = HCM_CHCC

USE [master]
ALTER
DATABASE HCM_CHUC
SET MULTI_USER;

ALTER DATABASE HCM_CHCC SET OFFLINE
GO
ALTER DATABASE HCM_CHCC MODIFY FILE (NAME =HCM_CHUC_Dat, FILENAME = 'D:\Data\HCM_CHCC.mdf')
GO
ALTER DATABASE HCM_CHCC MODIFY FILE (NAME =HCM_CHUC_Log, FILENAME = 'E:\Logs\HCM_CHCC.ldf')
GO
ALTER DATABASE databaseName SET ONLINE
GO

EXEC sp_databases