#
# Module manifest for module 'Microsoft.Security.Powershell.Cmdlets'
#
# Generated by: geoba 
#

@{

NestedModules     = "Microsoft.Security.Powershell.Cmdlets"
ModuleVersion     = "1.0.0.0"
GUID              = "{9765323d-6100-4545-8617-2dfda71f33af}"
Author            = "Microsoft Corporation"
CompanyName       = "Microsoft Corporation"
Copyright         = "(©) Microsoft Corporation. All rights reserved."
PowerShellVersion ='3.0'
CLRVersion        ='4.0'
CmdletsToExport   = @('Backup-SecurityPolicy', 'Restore-SecurityPolicy', 'Backup-AuditPolicy', 'Restore-AuditPolicy')
# HelpInfoUri     ="http://go.microsoft.com/fwlink/?linkid=390811"

}
